import { z } from 'zod'

const text = z.string().trim().min(1)
const id = text.regex(/^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$/)
const slug = text.regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)
const phase = z.object({ id, label: text, name: text.optional() }).strict()
const action = z.object({
  name: text, note: text.optional(), carryOver: z.boolean().optional(),
  noteLink: z.url().refine(value => /^https?:\/\//.test(value)).optional(),
}).strict()
const fightSchema = z.object({
  id: slug, name: text, shortName: text.optional(),
  type: z.enum(['Savage', 'Ultimate', 'Criterion', 'Other']),
  phases: z.array(phase).min(1),
}).strict()
const sheetSchema = z.object({
  id: slug, fightId: slug, name: text, updated: z.iso.date(),
  author: text.optional(), description: text.optional(), sourceFile: text.optional(), sourceVersion: text.optional(),
  source: z.object({ name: text, url: z.url().refine(value => /^https?:\/\//.test(value), 'Use an HTTP(S) source URL') }).strict().optional(),
  // `role` says which jobs may stand in this slot, so a generic assignment
  // ("Party Mit") can be resolved to the job the viewer actually plays.
  slots: z.array(z.object({ id, job: text.optional(), role: z.enum(['tank', 'healer', 'dps']).optional() }).strict()).min(1),
  phases: z.array(z.object({
    id,
    mechanics: z.array(z.object({
      id, name: text, time: text.regex(/^\d+:[0-5]\d$/).optional(),
      assignments: z.record(id, z.array(action).min(1)),
    }).strict()),
  }).strict()),
}).strict()

// Action name -> icon filename in public/icons. Generated by
// scripts/fetch_icons.py; an action with no entry renders text-only.
const iconsSchema = z.record(text, text.regex(/^\d{6}\.png$/, 'Icon must be a six-digit PNG filename'))

// Jobs, and what a sheet's generic ability names mean for each one.
const jobSchema = z.object({
  id: text.regex(/^[A-Z]{3}$/), name: text, role: z.enum(['tank', 'healer', 'dps']),
  abilities: z.record(text, text).optional(),
}).strict()
const jobsSchema = z.object({ jobs: z.array(jobSchema).min(1) }).strict()

export type Fight = z.infer<typeof fightSchema>
export type Sheet = z.infer<typeof sheetSchema>
export type Icons = z.infer<typeof iconsSchema>
export type Job = z.infer<typeof jobSchema>
export type Catalog = { fights: Fight[]; sheets: Sheet[]; icons: Icons; jobs: Job[] }

function unique(values: string[], label: string) {
  if (new Set(values).size !== values.length) throw new Error(`Duplicate ${label}`)
}

export function validateCatalog(files: Record<string, unknown>, rawIcons: unknown = {}, rawJobs: unknown = { jobs: [] }): Catalog {
  const icons = iconsSchema.parse(rawIcons)
  const { jobs } = jobsSchema.parse(rawJobs)
  unique(jobs.map(j => j.id), 'job IDs')
  const fights: Fight[] = []
  const sheets: Sheet[] = []
  for (const [path, value] of Object.entries(files)) {
    try {
      if (path.endsWith('/fight.json')) {
        const fight = fightSchema.parse(value)
        if (!path.endsWith(`/${fight.id}/fight.json`)) throw new Error('Fight ID must match its directory')
        unique(fight.phases.map(p => p.id), 'phase IDs')
        fights.push(fight)
      } else {
        const sheet = sheetSchema.parse(value)
        if (!path.endsWith(`/${sheet.fightId}/${sheet.id}.json`)) throw new Error('Sheet IDs must match its path')
        unique(sheet.slots.map(s => s.id), 'slot IDs')
        unique(sheet.phases.map(p => p.id), 'sheet phase IDs')
        unique(sheet.phases.flatMap(p => p.mechanics.map(m => m.id)), 'mechanic IDs')
        sheets.push(sheet)
      }
    } catch (error) { throw new Error(`${path}: ${String(error)}`) }
  }
  if (!fights.length) throw new Error('At least one fight is required')
  unique(fights.map(f => f.id), 'fight IDs')
  unique(sheets.map(s => `${s.fightId}/${s.id}`), 'sheet IDs')
  for (const sheet of sheets) {
    const fight = fights.find(f => f.id === sheet.fightId)
    if (!fight) throw new Error(`Unknown fight ${sheet.fightId}`)
    for (const phase of sheet.phases) {
      if (!fight.phases.some(p => p.id === phase.id)) throw new Error(`Unknown phase ${phase.id} in ${sheet.id}`)
      for (const mechanic of phase.mechanics) {
        for (const slot of Object.keys(mechanic.assignments)) {
          if (!sheet.slots.some(s => s.id === slot)) throw new Error(`Unknown slot ${slot} in ${mechanic.id}`)
        }
      }
    }
    sheet.phases.sort((a, b) => fight.phases.findIndex(p => p.id === a.id) - fight.phases.findIndex(p => p.id === b.id))
  }
  return { fights, sheets, icons, jobs }
}
